# Dockerfile.dev
FROM node:22-alpine

# Instalar versão específica do pnpm
RUN npm install -g pnpm@10.19.0

WORKDIR /app

# Copiar apenas os arquivos de configuração primeiro
COPY . .

# Instalar dependências
RUN CI=true pnpm install --no-frozen-lockfile

# Expor porta do Vite
EXPOSE 5173

# Comando para desenvolvimento
CMD ["pnpm", "run", "dev", "--host", "0.0.0.0"]
