services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "5174:5174"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5174"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s  # Dar mais tempo para iniciar
    stdin_open: false
    tty: false  # Desabilitar TTY para produção
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"