services:
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules  # Isso evita que node_modules seja sobrescrito
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Importante para hot reload no Docker
      - WATCHPACK_POLLING=true    # Para melhorar o watching de arquivos
    tty: true
    stdin_open: true
